### ISSUE TITLE
can not work on 1.10

### ISSUE THREAD

**Issue by StarchierOrb** [Dasfaust/GlobalMarket#137]
the plugin can not work on 1.10

[23:37:34 INFO]: [GlobalMarket] Enabling GlobalMarket v2.0.0.33
[23:37:34 ERROR]: Error occurred while enabling GlobalMarket v2.0.0.33 (Is it up to date?)
java.lang.NoSuchMethodError: com.comphenix.protocol.utility.MinecraftReflection.getBukkitItemStack(Lorg/bukkit/inventory/ItemStack;)Lorg/bukkit/inventory/ItemStack;
        at me.dasfaust.gm.trade.WrappedStack.<init>(WrappedStack.java:31) ~[?:?]
        at me.dasfaust.gm.config.Config.load(Config.java:227) ~[?:?]
        at me.dasfaust.gm.Core.onEnable(Core.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched.jar:git-TacoSpigot-"0934e8b"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched.jar:git-TacoSpigot-"0934e8b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-TacoSpigot-"0934e8b"]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched.jar:git-TacoSpigot-"0934e8b"]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched.jar:git-TacoSpigot-"0934e8b"]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:424) [patched.jar:git-TacoSpigot-"0934e8b"]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:389) [patched.jar:git-TacoSpigot-"0934e8b"]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:329) [patched.jar:git-TacoSpigot-"0934e8b"]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched.jar:git-TacoSpigot-"0934e8b"]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:590) [patched.jar:git-TacoSpigot-"0934e8b"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[23:37:34 INFO]: [GlobalMarket] Disabling GlobalMarket v2.0.0.33

**Comment by Dasfaust** [comment]
I am closing this issue as `wontfix`, as this repository is going to be archived. You are welcome to fork and republish the project, if you wish. I know this issue is very old, sorry for the ping!
